stages:
  - build
  - lint
  - codequality

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

before_script:
  - chmod +x ./gradlew

build_app:
  stage: build
  image: openjdk:11
  script:
    - ./gradlew :lite:assembleRelease
  artifacts:
    paths:
      - lite/build/outputs/

lint_checks:
  stage: lint
  image: openjdk:11
  script:
    - ./gradlew :lite:lint
    - ./gradlew :lite:fdroidLint || true
    - ./gradlew :lite:checkUpdates || true
  artifacts:
    paths:
      - lite/build/reports/
      - lite/build/outputs/lint-results.xml

codequality:
  stage: codequality
  image: stedolan/jq:latest
  script:
    - echo "Generating codequality.json..."
    - shopt -s nullglob
    - json_files=(lite/build/reports/**/*.json)
    - if [ ${#json_files[@]} -gt 0 ]; then
        jq '[.[]|.[]]' --slurp "${json_files[@]}" > codequality.json;
      else
        echo 'No JSON files found, creating empty codequality.json';
        echo '[]' > codequality.json;
      fi
  artifacts:
    paths:
      - codequality.json
